version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: apt update && apt-get -y install build-essential git sudo wget cmake libssl-dev libgmp-dev autoconf libtool
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake -DDISABLE_DOCKER_BUILDS=ON . && make
      - run: export GTEST_COLOR=1 && ctest -VV

  build_ledger_user:
    docker:
      - image: zondax/ledger-docker-bolos
    environment:
      - BOLOS_SDK=/root/project/deps/nanos-secure-sdk
      - BOLOS_ENV=/opt/bolos
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: make -C src/ledger-user

  build_ledger_val:
    docker:
      - image: zondax/ledger-docker-bolos
    environment:
      - BOLOS_SDK=/root/project/deps/nanos-secure-sdk
      - BOLOS_ENV=/opt/bolos
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: make -C src/ledger-val

  package_demo_user:
    docker:
      - image: zondax/ledger-docker-bolos
    environment:
      - BOLOS_SDK=/root/project/deps/nanos-secure-sdk
      - BOLOS_ENV=/opt/bolos
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: make -C src/ledger-user package
      - run: sudo apt-get -y install zip
      - run: zip -r demo_user_app.zip /root/project/src/ledger-user/pkgdemo
      - store_artifacts:
          path: demo_user_app.zip

  package_demo_val:
    docker:
      - image: zondax/ledger-docker-bolos
    environment:
      - BOLOS_SDK=/root/project/deps/nanos-secure-sdk
      - BOLOS_ENV=/opt/bolos
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: make -C src/ledger-val package
      - run: sudo apt-get -y install zip
      - run: zip -r demo_val_app.zip /root/project/src/ledger-val/pkgdemo
      - store_artifacts:
          path: demo_val_app.zip

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - build_ledger_user
      - build_ledger_val
      - package_demo_user:
          requires:
            - build
            - build_ledger_user
      - package_demo_val:
          requires:
            - build
            - build_ledger_val
